$axure.loadCurrentPage({
  "url":"page_1.html",
  "generationDate":new Date(1568687273858.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"PercIncreaseNum",
"PercCalcValue"],
  "page":{
    "packageId":"7761ed2c68604df085d0e9f60b24cd06",
    "type":"Axure:Page",
    "name":"Page 1",
    "notes":{
      "Default":"<p><span>This interface is based on the familiarity of Google Maps which helps to reduce the learning curve for users. In fact, the only new features implemented are an icon in the top bar to switch between screens and a fuel gauge to show the amount of fuel remaining as a percentage. The fuel gauge will be different colors depending on amount of fuel consumed (0-25% red, 26-80% yellow, and 80-100% green). The map will be programmed to display two routes: the route with the least amount of fuel consumed and the route with the most fuel consumed for the timeframe selected in the menu. The design was made using the Android icon library but can easily be modified to conform to other devices. There are several ways to validate my design including random sampling of users to perform user experience testing and complete surveys of about the interface. I can also ask experts in navigation systems design to evaluate my prototype. To do this, I will provide a list of criteria in the form of questions to the experts who will perform a heuristic analysis of the interface. I will ask the following questions:</span></p><p><span>1. Is the interface easy to navigate?</span></p><p><span>2. Is the fuel indicator clear and easy to understand?</span></p><p><span>3. Are there sufficient visual cues? </span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"Hide Select Time Interval",
                "objectsToFades":[{
                    "objectPath":["2dd6c1a5d44948bc8ecb526ab2a13d2b"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"fadeWidget",
                "description":"Show/Hide Widget",
                "objectsToFades":[]}]}]}},
    "diagram":{
      "objects":[{
          "id":"52dc511781744402ba0448bbe0725fa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":310},
            "size":{
              "width":169,
              "height":32}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":682,
                "y":198}}},
          "objects":[{
              "id":"7f49d639237d4385bf58a149635300cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":461,
                  "y":310},
                "size":{
                  "width":169,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"d69cf60496aa4112bea2cb40ac341eed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":130},
            "size":{
              "width":222,
              "height":450}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":0},
              "size":{
                "width":672,
                "height":384}}},
          "objects":[{
              "id":"a0b4a759a2484c459ba654d5b216f14f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":130},
                "size":{
                  "width":222,
                  "height":450}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/page_1/u2.jpg",
            "normal~a":"images/page_1/u2.jpg"}},
{
          "id":"b59ae948402d4a8a8286e306fe8a3a52",
          "label":"Rectangle",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":373,
              "y":493},
            "size":{
              "width":54,
              "height":51},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC00}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":469,
                "y":310},
              "size":{
                "width":164,
                "height":43}}},
          "objects":[{
              "id":"62b0d79e755d4d87ae34c8dcbcf3ad14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":373,
                  "y":493},
                "size":{
                  "width":54,
                  "height":51},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00}},
              "adaptiveStyles":{
                "a":{
}}}],
          "annotation":{
            "Description":"Guage Wheel showing percentage. Wheel will change color from red for 0-25%, yellow for 26-80%, and green for 80-100%. It goes down as a person drives the car",
            "Benefit":"Critical"},
          "images":{
            "normal~":"images/page_1/rectangle_u4.png",
            "normal~a":"images/page_1/rectangle_u4_a.png"}},
{
          "id":"412fc2dc010b42bc9838e81d53a6659c",
          "label":"Text",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":367,
              "y":508},
            "size":{
              "width":73,
              "height":42},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":507,
                "y":310}}},
          "objects":[{
              "id":"2eb4d3f391a049d499c38418755cd93b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":367,
                  "y":508},
                "size":{
                  "width":73,
                  "height":42},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"2fc321779864463e9942dcec435d8acc",
          "label":"Text",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":450,
              "y":509},
            "size":{
              "width":110,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":682,
                "y":301}}},
          "objects":[{
              "id":"0e88c898dd164400a59542bafd020661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":509},
                "size":{
                  "width":110,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"e2997c9fbc964758b2c4a5fca389cd61",
          "label":"Select Time Interval",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":160},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":581,
                "y":26},
              "size":{
                "width":61,
                "height":20}}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"Show Select Time Interval slide down 500 ms",
                      "objectsToFades":[{
                          "objectPath":["2dd6c1a5d44948bc8ecb526ab2a13d2b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]},
{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide Select Time Interval slide up 500 ms",
                      "objectsToFades":[{
                          "objectPath":["2dd6c1a5d44948bc8ecb526ab2a13d2b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f4227a8393c84e5684c9684bb78a1ab9",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"441dce7ae1d2435eb4ef87a7b85a897b",
                  "label":"",
                  "parentDynamicPanel":"e2997c9fbc964758b2c4a5fca389cd61",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"1959c6b3c1ac444eb2e59ae1a2a51f4d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e2997c9fbc964758b2c4a5fca389cd61",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "annotation":{
                    "Description":"Select Time Interval",
                    "Benefit":"Critical"},
                  "images":{
                    "normal~":"images/page_1/u11.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"2dd6c1a5d44948bc8ecb526ab2a13d2b",
          "label":"Select Time Interval",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":190},
            "size":{
              "width":305,
              "height":319}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":369,
                "y":51}}},
          "objects":[{
              "id":"5676623fa0e64dd8b820996a4721dfda",
              "label":"Select Time Interval",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":305,
                  "height":319}},
              "adaptiveStyles":{
                "a":{
}},
              "objects":[{
                  "id":"f61baa88a5894535b16e38233a37a1b1",
                  "label":"Yesterday",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}},
                      "selected":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":305,
                      "height":53}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"ec489fc6ead2481d8497a2b61539b9c7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}},
                          "selected":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":305,
                          "height":53}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "annotation":{
                    "Description":"Upon selection, map display routes consuming the least and most fuel respectively yesterday",
                    "Benefit":"Critical"},
                  "images":{
                    "normal~":"images/page_1/yesterday_u15.png",
                    "selected~":"images/page_1/yesterday_u15_selected.png",
                    "mouseOver~":"images/page_1/yesterday_u15.png",
                    "mouseDown~":"images/page_1/yesterday_u15_selected.png"}},
{
                  "id":"e1dd4835edf448ea82d14489d852e5ce",
                  "label":"Last Week",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}},
                      "selected":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":53},
                    "size":{
                      "width":305,
                      "height":57}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"d03dcc927069420697b8f72dc2f49101",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}},
                          "selected":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":53},
                        "size":{
                          "width":305,
                          "height":57}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "annotation":{
                    "Description":"Upon selection, map display routes consuming the least and most fuel respectively over the last week",
                    "Benefit":"Critical"},
                  "images":{
                    "normal~":"images/page_1/last_week_u17.png",
                    "selected~":"images/page_1/last_week_u17_selected.png",
                    "mouseOver~":"images/page_1/last_week_u17.png",
                    "mouseDown~":"images/page_1/last_week_u17_selected.png"}},
{
                  "id":"9155b8c2ad7d4e878c0f3e130fb43df8",
                  "label":"Last Month",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}},
                      "selected":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":110},
                    "size":{
                      "width":305,
                      "height":66}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"57192d184a694e9295c3b6fb5541534a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}},
                          "selected":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":110},
                        "size":{
                          "width":305,
                          "height":66}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "annotation":{
                    "Description":"Upon selection, map display routes consuming the least and most fuel respectively over the last month",
                    "Benefit":"Critical"},
                  "images":{
                    "normal~":"images/page_1/last_month_u19.png",
                    "selected~":"images/page_1/last_month_u19_selected.png",
                    "mouseOver~":"images/page_1/last_month_u19.png",
                    "mouseDown~":"images/page_1/last_month_u19_selected.png"}},
{
                  "id":"c459cf31822c4c67b017e1a1006451f5",
                  "label":"Last 6 months",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}},
                      "selected":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":176},
                    "size":{
                      "width":305,
                      "height":143}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"00a0d2fbee5141068306019a34308426",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}},
                          "selected":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":176},
                        "size":{
                          "width":305,
                          "height":143}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "annotation":{
                    "Description":"Upon selection, map display routes consuming the least and most fuel respectively over the last 6 months",
                    "Benefit":"Critical"},
                  "images":{
                    "normal~":"images/page_1/last_6_months_u21.png",
                    "selected~":"images/page_1/last_6_months_u21_selected.png",
                    "mouseOver~":"images/page_1/last_6_months_u21.png",
                    "mouseDown~":"images/page_1/last_6_months_u21_selected.png"}}],
              "annotation":{
                "Description":"Upon selection, map display routes consuming the least and most fuel respectively.",
                "Benefit":"Critical"}}]},
{
          "id":"ee7f8e810e5d451fae8ba1e6f233c9d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":614},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":158,
                "y":410}}},
          "objects":[{
              "id":"a455011289594bf5a6abfc812609e39f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":614},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"4bad26f349c04e75a8b3a606d94b0c9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":160},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":682,
                "y":26}}},
          "objects":[{
              "id":"845fdf1dfcf84c7aa575c51233e61115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":160},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"4ba984d541c849aead4b894140f4df29",
          "label":"Favourites",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":160},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":491,
                "y":26},
              "size":{
                "width":61,
                "height":17}}},
          "objects":[{
              "id":"59bb440ee05a47eca0c0633dc0f9200b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":160},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
                "a":{
}}}],
          "annotation":{
            "Description":"Allows user to switch to other view. Icon will change depending on current view.",
            "Benefit":"Critical"},
          "images":{
            "normal~":"images/page_1/favourites_u27.png",
            "normal~a":"images/page_1/favourites_u27.png"}},
{
          "id":"ebb6cc3b2d954cfabc948c6b03651312",
          "label":"Bottom Navigation Bar",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":545},
            "size":{
              "width":222,
              "height":35}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":354},
              "size":{
                "width":672,
                "height":30}}},
          "objects":[{
              "id":"eecbc8ba1d6a4cecb733018ba4b60369",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":545},
                "size":{
                  "width":222,
                  "height":35}},
              "adaptiveStyles":{
                "a":{
}}}],
          "annotation":{
            "Description":"Navigation bar with back arrow, minimize (center circle) and&nbsp; application switcher (rectangular box)",
            "Benefit":"Critical"},
          "images":{
            "normal~":"images/page_1/bottom_navigation_bar_u29.png",
            "normal~a":"images/page_1/bottom_navigation_bar_u29.png"}},
{
          "id":"1e8dfc295458478abc9772cc5899eaea",
          "label":"Text",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":454,
              "y":553},
            "size":{
              "width":104,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":682,
                "y":354}}},
          "objects":[{
              "id":"e03e9f6d15e2480da9617be0e0a036c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":454,
                  "y":553},
                "size":{
                  "width":104,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"a411a731cbfb47b4a0942018c2dde514",
          "label":"Go to Favourites",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":482},
            "size":{
              "width":48,
              "height":48},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "stateStyles":{
                "disabled":{
                  "opacity":"0",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF999999}}},
              "limbo":false}},
          "objects":[{
              "id":"dc60bb2d3a414cf487c431180fd25155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":482},
                "size":{
                  "width":48,
                  "height":48},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "annotation":{
            "Description":"This button takes the user to favourites when viewing the prototype in a web brower. It is not part of the application design. ",
            "Benefit":"Useful"},
          "images":{
            "normal~":"images/page_1/go_to_favourites_u33.png",
            "normal~a":"images/page_1/go_to_favourites_u33.png",
            "disabled~a":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "52dc511781744402ba0448bbe0725fa5":{
      "scriptId":"u0"},
    "7f49d639237d4385bf58a149635300cf":{
      "scriptId":"u1"},
    "d69cf60496aa4112bea2cb40ac341eed":{
      "scriptId":"u2"},
    "a0b4a759a2484c459ba654d5b216f14f":{
      "scriptId":"u3"},
    "b59ae948402d4a8a8286e306fe8a3a52":{
      "scriptId":"u4"},
    "62b0d79e755d4d87ae34c8dcbcf3ad14":{
      "scriptId":"u5"},
    "412fc2dc010b42bc9838e81d53a6659c":{
      "scriptId":"u6"},
    "2eb4d3f391a049d499c38418755cd93b":{
      "scriptId":"u7"},
    "2fc321779864463e9942dcec435d8acc":{
      "scriptId":"u8"},
    "0e88c898dd164400a59542bafd020661":{
      "scriptId":"u9"},
    "e2997c9fbc964758b2c4a5fca389cd61":{
      "scriptId":"u10"},
    "441dce7ae1d2435eb4ef87a7b85a897b":{
      "scriptId":"u11"},
    "1959c6b3c1ac444eb2e59ae1a2a51f4d":{
      "scriptId":"u12"},
    "2dd6c1a5d44948bc8ecb526ab2a13d2b":{
      "scriptId":"u13"},
    "5676623fa0e64dd8b820996a4721dfda":{
      "scriptId":"u14"},
    "f61baa88a5894535b16e38233a37a1b1":{
      "scriptId":"u15"},
    "ec489fc6ead2481d8497a2b61539b9c7":{
      "scriptId":"u16"},
    "e1dd4835edf448ea82d14489d852e5ce":{
      "scriptId":"u17"},
    "d03dcc927069420697b8f72dc2f49101":{
      "scriptId":"u18"},
    "9155b8c2ad7d4e878c0f3e130fb43df8":{
      "scriptId":"u19"},
    "57192d184a694e9295c3b6fb5541534a":{
      "scriptId":"u20"},
    "c459cf31822c4c67b017e1a1006451f5":{
      "scriptId":"u21"},
    "00a0d2fbee5141068306019a34308426":{
      "scriptId":"u22"},
    "ee7f8e810e5d451fae8ba1e6f233c9d2":{
      "scriptId":"u23"},
    "a455011289594bf5a6abfc812609e39f":{
      "scriptId":"u24"},
    "4bad26f349c04e75a8b3a606d94b0c9b":{
      "scriptId":"u25"},
    "845fdf1dfcf84c7aa575c51233e61115":{
      "scriptId":"u26"},
    "4ba984d541c849aead4b894140f4df29":{
      "scriptId":"u27"},
    "59bb440ee05a47eca0c0633dc0f9200b":{
      "scriptId":"u28"},
    "ebb6cc3b2d954cfabc948c6b03651312":{
      "scriptId":"u29"},
    "eecbc8ba1d6a4cecb733018ba4b60369":{
      "scriptId":"u30"},
    "1e8dfc295458478abc9772cc5899eaea":{
      "scriptId":"u31"},
    "e03e9f6d15e2480da9617be0e0a036c9":{
      "scriptId":"u32"},
    "a411a731cbfb47b4a0942018c2dde514":{
      "scriptId":"u33"},
    "dc60bb2d3a414cf487c431180fd25155":{
      "scriptId":"u34"}}});